### ISSUE TITLE
Use SHA256 instead of SHA1

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phar-site-generator#4]

**Comment by sebastianbergmann** [comment]
Moved here from https://github.com/sebastianbergmann/phpunit/issues/1889

**Comment by avindra** [comment]
Thanks-I can give it a shot myself after work today.

**Comment by sebastianbergmann** [comment]
Sure, go ahead, 194ae84c9434364f117d8961dac3e729a6bbb4ce should serve as a starting point. Just make sure that the layout does not break.
