### ISSUE TITLE
Support for GitHub Pages

### ISSUE THREAD

**Issue by filips123** [sebastianbergmann/phar-site-generator#7]
It is possible to use this tool with GitHub Pages?

You should be able to set up CI that would run tool and then publish changes to GitHub Pages.

**Comment by sebastianbergmann** [comment]
This tool is what it is: a static site generator. How the static assets generated by this tool are hosted is outside the scope of this tool.

**Comment by filips123** [comment]
README says:

> This tool makes the following assumptions:
> * The PHAR repository is hosted using nginx

And it also requires nginx in configuration file.

So what does this mean? How to just set up static build that can be hosted anywhere?
